# Generated by Django 2.0.4 on 2018-04-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('poster_path', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('overview', models.CharField(max_length=600)),
                ('runtime', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
            ],
        ),
    ]
