# Generated by Django 2.0.4 on 2018-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0005_cast_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(default=0)),
                ('cast_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cast',
            name='movieId',
        ),
    ]
