# Generated by Django 2.0.4 on 2018-04-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0006_auto_20180415_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='movie',
        ),
    ]
