# Generated by Django 2.0.4 on 2018-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0007_remove_cast_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='birth_date',
            field=models.CharField(default='1989-11-11', max_length=200),
        ),
        migrations.AddField(
            model_name='cast',
            name='birth_place',
            field=models.CharField(default='АҚШ', max_length=200),
        ),
        migrations.AddField(
            model_name='cast',
            name='gender',
            field=models.CharField(default='Еркек', max_length=200),
        ),
        migrations.AddField(
            model_name='cast',
            name='job',
            field=models.CharField(default='Актер', max_length=200),
        ),
    ]
