# Generated by Django 2.0.4 on 2018-04-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0008_auto_20180415_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('concept', models.CharField(max_length=200)),
                ('poster_path', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=200)),
                ('viewCnt', models.IntegerField(default=0)),
            ],
        ),
    ]
