# Generated by Django 2.0.4 on 2018-04-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0011_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('movieid', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='seen',
            name='movieid',
        ),
        migrations.DeleteModel(
            name='Seen',
        ),
    ]
