# Generated by Django 2.0.4 on 2018-04-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0012_auto_20180420_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovies',
            name='movieid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='responses.Movie'),
        ),
    ]
