# Generated by Django 2.0.4 on 2018-04-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0013_auto_20180420_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovies',
            name='movieid',
            field=models.IntegerField(default=0),
        ),
    ]
